export const _init = {
  query: {
    language: "s",
    region: "s",
    sort_by: "popularity.desc",
    certification_country: "S",
    certification: {
      DEFAULT: "",
      lte: "v",
      gte: "v",
    },
    include_adult: false,
    include_video: false,
    page: "1",
    primary_release_year: "",
    primary_release_date: {
      lte: "v",
      gte: "v",
    },
    release_date: {
      lte: "v",
      gte: "v",
    },
    with_release_type: 0,
    year: 0,
    vote_count: {
      lte: "v",
      gte: "v",
    },
    vote_average: {
      lte: "v",
      gte: "v",
    },
    with_cast: "S",
    with_crew: "S",
    with_people: "S",
    with_companies: "S",
    with_genres: "S",
    without_genres: "S",
    with_keywords: "S",
    without_keywords: "S",
    with_runtime: {
      lte: "v",
      gte: "v",
    },
    with_original_language: "S",
    with_watch_providers: "S",
    watch_region: "S",
    with_watch_monetization_types: false,
    without_companies: "S",
  },
};
